#!/bin/bash

FILE="$HOME/.cache/eww_launch.bar"
EWW=`which eww`
CFG="$HOME/.config/eww/arin"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --restart --config "$CFG" open-many \
		   search apps weather music system
}


## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close search apps weather music system
	rm "$FILE"
fi
