#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music \
					reddit youtube weather mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--rd" ]]; then
	close_dash && kitty tuir &
elif [[ "$1" == "--yt" ]]; then
	close_dash && kitty yt &
elif [[ "$1" == "--mail" ]]; then
	close_dash && kitty nmail -d ~/.config/nmail &
fi
