#!/bin/bash

if [ -z "$PROJECTS_FOLDER" ]; then
  echo "Need to set PROJECT_FOLDER"
  exit 1
fi

PROJECTS="$PROJECTS_FOLDER/*"

for D in $PROJECTS; do
  if [ -d "$D" ] && [ -f "$D/commit" ]; then
    echo "IN $D"
    cd "$D"
    MESSAGE=$(cat "$D/commit")
    rm "$D/commit"
    git add .
    git commit -m "$MESSAGE"
    git push origin master
  fi
done
