#! /bin/sh

sxhkd &
compton &
$HOME/.config/lemonbar/bar.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          38

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color \#4c566a
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#d8dee9

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

exec hsetroot -solid "#434c5e"
